local use = {
	"dashboard",
	"lualine",
	"bufferline",
	"telescope",
	"filetype",
	"nvim-tree",
	"nvim-web-devicons",
	"lspkind",
	"symbols-outline",
	"lspsaga",
	"nvim-ts-rainbow",
	"fidget",
	"lsp_signature",
	"vim-smoothie",
	"Comment",
	"nvim-ts-context-commentstring",
	"accelerated-jk",
	"vim-eft",
	"incsearch",
	"indent-guides",
	"nvim-colorizer",
}
return use